#!/bin/bash

DEFAULT_OUTPUT=${PWD}/build.tar;
TAG=hackthe6ix/landing-2020;
WORKING_DIR=/usr/var/app;
NAME=owo;

function dev() {
    while getopts r:s:v:p: flag
    do
        case "${flag}" in
            # static folder
            r) r=${OPTARG};;
            # src folder
            s) s=${OPTARG};;
            # docker tag version
            v) v=${OPTARG};;
            # host port to run on
            p) p=${OPTARG};;
        esac
    done

    local tag=$TAG\:${v:-latest};

    docker build --target development -t $tag .;
    docker run \
        -v ${PWD}/static:${r:-$WORKING_DIR/static} \
        -v ${PWD}/src:${s:-$WORKING_DIR/src} \
        -p ${p:-8080}:8080 \
        -it $tag;
}

function test() {
    while getopts r:s:v: flag
    do
        case "${flag}" in
            # static folder
            r) r=${OPTARG};;
            # src folder
            s) s=${OPTARG};;
            # docker tag version
            v) v=${OPTARG};;
        esac
    done

    local tag=$TAG:${v:-latest};

    docker build --target testing -t $tag .;
    docker run \
        -v ${PWD}/static:${r:-$WORKING_DIR/static} \
        -v ${PWD}/src:${s:-$WORKING_DIR/src} \
        $tag;
}

function export() {
    while getopts r:s:v:o: flag
    do
        case "${flag}" in
            # docker tag version
            v) v=${OPTARG};;
            # output file/dir
            o) o=${OPTARG};;
        esac
    done

    local output=${o:-$DEFAULT_OUTPUT};
    if [[ $output == *.tar ]]
    then
        type=tar;
    else
        type=local;
    fi

    DOCKER_BUILDKIT=1 docker build \
        --output type=$type,dest=$output \
        --target 'export' \
        -t tag=$TAG\:${v:-latest} .;
}

function serve() {
    while getopts v:o:p: flag
    do
        case "${flag}" in
            # docker tag version
            v) v=${OPTARG};;
            # Server name
            o) o=${OPTARG};;
            # Port to run from
            p) p=${OPTARG};;
        esac
    done

    local tag=$TAG\:${v:-latest};
    local port=${p:-80};

    docker build --target deploy -t $tag .;
    docker run \
        -p ${port}:80 \
        -e SERVER_NAME=${o:-_} \
        $tag;
}

eval "$@ && exit 0";
